### ISSUE TITLE
test failures on python 3.10 due to PyDict_GetItem()

### ISSUE THREAD

**Issue by davide125** [osandov/drgn#101]
Pretty much all tests fail on Python 3.10 with a
```
    from _drgn import (
E   ImportError: /builddir/build/BUILDROOT/python-drgn-0.0.11-2.fc35.x86_64/usr/lib64/python3.10/site-packages/_drgn.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyDict_GetItemId
```
which looks like is a side effect of the change applied in https://bugs.python.org/issue40839 which now requires to hold the GIL when calling this.

See https://bugzilla.redhat.com/show_bug.cgi?id=1948977 for more details and the full error logs.

**Comment by osandov** [comment]
I think this is actually because python/cpython@fb5db7ec58624cab0797b4050735be865d380823 remove `_PyDict_GetItemId()`. Looks like we should use `_PyDict_GetItemIdWithError()` instead. I'll fix that up today or tomorrow.
