### ISSUE TITLE
drgn cannot process new Fedora kernels?

### ISSUE THREAD

**Issue by vaverin** [osandov/drgn#104]
[root@localhost test]# rpm -q drgn
drgn-0.0.11-2.fc35.x86_64
[root@localhost test]# drgn -s /usr/lib/debug/lib/modules/5.12.0-0.rc8.191.fc35.x86_64/vmlinux 
Traceback (most recent call last):
  File "/usr/bin/drgn", line 33, in <module>
    sys.exit(load_entry_point('drgn==0.0.11', 'console_scripts', 'drgn')())
  File "/usr/lib64/python3.9/site-packages/drgn/internal/cli.py", line 119, in main
    prog.load_debug_info(args.symbols, **args.default_symbols)
Exception: /usr/lib/debug/usr/lib/modules/5.12.0-0.rc8.191.fc35.x86_64/vmlinux: .debug_info+0x7704ab: unknown DWARF CU version 5

[root@localhost test]# drgn -s /usr/lib/debug/lib/modules/5.11.12-300.fc34.x86_64/vmlinux 
Traceback (most recent call last):
  File "/usr/bin/drgn", line 33, in <module>
    sys.exit(load_entry_point('drgn==0.0.11', 'console_scripts', 'drgn')())
  File "/usr/lib64/python3.9/site-packages/drgn/internal/cli.py", line 119, in main
    prog.load_debug_info(args.symbols, **args.default_symbols)
Exception: /usr/lib/debug/usr/lib/modules/5.11.12-300.fc34.x86_64/vmlinux: .debug_info+0xc393a3: unknown DWARF CU version 5

**Comment by osandov** [comment]
Fedora must be using DWARF 5 now. drgn doesn't support it yet, but it shouldn't be a ton of work to implement it. I'll add it to my to-do list, thanks for the report.

**Comment by osandov** [comment]
I just pushed support for DWARF 5. Please try it out if you get the chance!
