### ISSUE TITLE
drgn -c doesn't work: not an ELF file

### ISSUE THREAD

**Issue by mishuang2017** [osandov/drgn#12]
drgn -k works. But I also want to debug the core dump. But it doesn't work.

$ file vmcore
vmcore: Kdump compressed dump v6, system Linux, node dev-r630-04, release 4.19.36+, version #96 SMP Thu Aug 15 14:50:12 CST 2019, machine x86_64, domain lab.mtl.com
$ drgn -c ./vmcore
Traceback (most recent call last):
  File "/usr/local/bin/drgn", line 11, in <module>
    load_entry_point('drgn==0.0.1', 'console_scripts', 'drgn')()
  File "/usr/local/lib64/python3.6/site-packages/drgn-0.0.1-py3.6-linux-x86_64.egg/drgn/internal/cli.py", line 83, in main
    prog.set_core_dump(args.core)
_drgn.FileFormatError: not an ELF file

Maybe because the vmcore is compressed. If it is the reason, then it there a way to uncompress it?

**Comment by osandov** [comment]
For kdump support, you'll need to install libkdumpfile and rebuild drgn. There's a link in the readme, but let me know if you need help.

**Comment by osandov** [comment]
Actually, come to think of it, that should've reported an error indicating that drgn wasn't built with kdump support. Could you please share the output of `xxd vmcore | head`?

**Comment by mishuang2017** [comment]
$ xxd vmcore | head
00000000: 4b44 554d 5020 2020 0600 0000 4c69 6e75  KDUMP   ....Linu
00000010: 7800 0000 0000 0000 0000 0000 0000 0000  x...............
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0064 6576  .............dev
00000050: 2d72 3633 302d 3034 2e6d 7462 632e 6c61  -r630-04.mtbc.la
00000060: 6273 2e6d 6c6e 7800 0000 0000 0000 0000  bs.mlnx.........
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 342e  ..............4.
00000090: 3139 2e33 362b 0000 0000 0000 0000 0000  19.36+..........

**Comment by osandov** [comment]
That's really strange, it has the kdump signature. I don't see any obvious bugs in the code. I'll try to reproduce this tomorrow, thanks for the report.

**Comment by mishuang2017** [comment]
Thanks for quick reply.

**Comment by mishuang2017** [comment]
My drgn source code is a little old. After pulling the latest code and installing libkdumpfile, now it works.

# drgn -c ./vmcore
drgn 0.0.1 (using Python 3.6.6)
For help, type help(drgn).
>>> import drgn
>>> from drgn import cast, container_of, execscript, NULL, Object, reinterpret
>>> from drgn.helpers.linux import *
>>> dev_base_head = prog['init_net'].dev_base_head.address_of_()
>>> print(dev_base_head)
*(struct list_head *)0xffffffff933e6890 = {
        .next = (struct list_head *)0xffff929c19f10050,
        .prev = (struct list_head *)0xffff929b87fca050,
}
>>>
