### ISSUE TITLE
Listing variables in a stack frame

### ISSUE THREAD

**Issue by brenns10** [osandov/drgn#134]
Something I'm only now realizing about drgn is how powerful the stack traces are! The stack frame `__getitem__` is quite useful for looking up variables -- sometimes you get lucky and can actually read the value of a variable from the stack.

From the perspective of a debugger, this has the potential to be very useful, and one thing I'd want to do is be able to write my own custom stack trace formatter, which could list out any variable values which we have data for. But right now you need to know the name of a variable in order to get its value. There's no equivalent `StackFrame.variables()` to serve as an analog for `StackFrame.registers()`.

From my reading of the `dwarf_info.c`, it seems like I could take a similar approach to `drgn_find_in_dwarf_scopes()`:

1. Iterate over the scopes in the stack frame.
2. Find child DIEs, and for those which are variable or formal_parameter tagged, add them to some list.
3. Stop iterating when you get to scope that's too high level (e.g. the whole compilation unit).
4. Return the list as drgn_objects.

For the Python API, I'm proposing roughly:

```
StackTrace.variables()

Returns a dict of function arguments and local variables, mapping their names 
to Objects. Many of these objects may be absent, meaning they are compiled 
out, or drgn is otherwise unable to determine their values.
```

I've started a WIP branch (not functional yet) to do this, but I wanted to post an issue first to see whether the API is good and whether it would be worth including. If so, I'd like to figure out number 3 above: when do we stop including variables? For C, it makes sense to stop at the compilation unit. But for other languages, there may be other scope types (namespaces? class variables), so I'd want to consider them too.

**Comment by osandov** [comment]
I have plans to add exactly this as part of #123, which will also provide similar functionality for listing variables in namespaces (including the global namespace for C).

**Comment by osandov** [comment]
I have some work-in-progress code for that which I'm planning to get back to after the holidays.

**Comment by brenns10** [comment]
Oh awesome! I recall thinking something along the lines of "wow, I bet visibility into the scopes themselves would be nice too..." when I was reading through the code. I think I saw that issue before as well, but didn't make the connection with stack frames (I kinda assumed it was mainly a C++ thing). Glad I asked before committing too much time. I'll close this up in favor of #123.
