### ISSUE TITLE
Add name to drgn.Thread

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#143]
Follow-up to #92. Let's add a `drgn.Thread.name` attribute which is the name of the thread.

* For the Linux kernel, this can be retrieved from `struct task_struct::comm`.
* For live userspace processes, this can be retrieved from `/proc/$tid/comm` or `/proc/$pid/task/$tid/comm`.
* For userspace core dumps, the name of the main thread is saved as the `fname` field of the `PRPSINFO` note:

```console
$ eu-readelf -n crashme_multithreaded_core | grep -A 3 PRPSINFO
  CORE                 136  PRPSINFO
    state: 2, sname: D, zomb: 0, nice: 0, flag: 0x0000000040400404
    uid: 1000, gid: 985, pid: 39143, ppid: 39053, pgrp: 39143, sid: 39053
    fname: crashme_multith, psargs: ./crashme_multithreaded 
```

Unfortunately, the names of other threads don't appear to be saved in the core dump.

I think this is more or less the Python API we want:

```python
class Thread:
    name: Optional[str]
    """
    Thread name, or ``None`` if unknown.

    See `PR_SET_NAME
    <https://man7.org/linux/man-pages/man2/PR_SET_NAME.2const.html>`_
    and `/proc/[pid]/comm
    <https://man7.org/linux/man-pages/man5/proc_pid_comm.5.html>`_.

    .. note::
        Linux userspace core dumps only save the name of the main thread, so
        :attr:`name` will be ``None`` for other threads.
    """
```

This would be implemented in the Python bindings on top of a C API. There are a few options for the C API:

1. Get the thread name eagerly from the above sources, store it in `struct drgn_thread`, and return it from a simple getter `const char *drgn_thread_name(struct drgn_thread *thread)`. The returned string is owned by the `struct drgn_thread`.
2. Get the thread name when it is requested with `struct drgn_error *drgn_thread_name(struct drgn_thread *thread, char **ret)`. The caller is responsible for freeing the returned string.
3. Get the thread name when it is requested, but also cache it in `struct drgn_thread` for subsequent calls.

I'm leaning towards option 2, although it's up for debate.

**Comment by rtadepalli** [comment]
Hi @osandov , I'd like to try my hand at this, if it is still available to pick up. Thanks.

**Comment by osandov** [comment]
Yes, it is still available, thank you! Let me know if you need any help getting started.
