### ISSUE TITLE
[Question] Looking at program at different instances of time with drgn

### ISSUE THREAD

**Issue by sidkshatriya** [osandov/drgn#149]
Thanks for drgn! I have question about drgn, and I would be grateful if you were able to answer it.

Let's say I have a live pid 1234. I can create a Program in drgn via `drgn.program_from_pid(1234)`. This will process `/proc/1234/mem` and load the debug symbols. Now I proceed to extract some data from the program via my Python code and then I'm done but I don't exit out of drgn -- I'm running drgn in some sort of server loop. 

Some time elapses, pid 1234 does some work and is now paused again (I do that separately without drgn's intervention -- I am controlling pid 1234 via an external program). I _could_ create a fresh Program instance via `drgn.program_from_pid(1234)` again but this does some wasteful work. It's OK that drgn needs to process `/proc/1234/mem` again (the memory contents would have changed, the memory mapping may have changed). However drgn needs to load the debug symbols all over again and process that and this is potentially repeated work.

Is there a way I could simply use the previous Program instance's debug info? Or somehow tell an already created drgn Program object to "refresh" itself. Does my question make sense? Or is there something else happening under the hood that I would compulsorily need to create a fresh Program object?

**Comment by osandov** [comment]
drgn was built with live debugging use cases like this in mind, so it explicitly won't cache any memory it reads: every time you access something in memory, drgn will get a fresh view of it. So, you shouldn't need a new `Program` object, and you don't need to explicitly refresh it, either.

The one caveat is that although "reference" objects are read from memory every time, "value" objects hold a fixed value. You can read more about the difference here: https://drgn.readthedocs.io/en/latest/user_guide.html#objects. The main difference for you is that this will work:

```pycon
>>> my_var = prog["my_var"]
>>> my_var
... original value
# restart program, wait for it to pause again
>>> my_var
... new value
```

But if you do something like a computation with the variable, this creates a value object, which won't refresh:

```pycon
>>> my_var_plus_one = prog["my_var"] + 1
>>> my_var_plus_one
... original value + 1
# restart program, wait for it to pause again
>>> my_var_plus_one
... still the original value + 1
```

**Comment by sidkshatriya** [comment]
Thanks for your reply!

> drgn was built with live debugging use cases like this in mind, so it explicitly won't cache any memory it reads:

So drgn will be able to handle the case that there is (for example) a new mmap region for process? So if I try to read something from the new memory region, drgn will not trip up?

> The one caveat is that although "reference" objects are read from memory every time, "value" objects hold a fixed value.

Cool -- understood.

**Comment by osandov** [comment]
> Thanks for your reply!
> 
> > drgn was built with live debugging use cases like this in mind, so it explicitly won't cache any memory it reads:
> 
> So drgn will be able to handle the case that there is (for example) a new mmap region for process? So if I try to read something from the new memory region, drgn will not trip up?

Correct, new mmap regions should be fine.

**Comment by sidkshatriya** [comment]
Thanks!
