### ISSUE TITLE
do your example works too for systemd ?

### ISSUE THREAD

**Issue by Azaretdodo** [osandov/drgn#175]
hello,

firstly i am fall this error with your example : 

```
>>> from drgn.helpers.linux import list_for_each_entry
>>> for mod in list_for_each_entry('struct module',
...                                 prog['modules'].address_of_(),
...                                 'list'):
...     if mod.refcnt.counter > 10:
...         print(mod.name)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'prog' is not defined
```
now i have reach the wall with your example can you help myself fully run your script ?

i think your code need thoses : 

`def ( prog ) : 
`

after reach my own error i have try other line of command for fall at the ground...

thank you in advance for your smart answer for repair your script,

i am in install the last kernel for do your example too i am interested to do your example with the last systemd thus do your example work for the last systemd ?

your example : 

```
>>> from drgn.helpers.linux import list_for_each_entry
>>> for mod in list_for_each_entry('struct module',
...                                prog['modules'].address_of_(),
...                                'list'):
...    if mod.refcnt.counter > 10:
...        print(mod.name)
...
```

thank you in advance for your soon answer interesting,

Regards.

Azaretdodo.

**Comment by osandov** [comment]
Hello, please see the quick start documentation: https://github.com/osandov/drgn#quick-start. Running the drgn CLI with those directions will create the `prog` variable.

That example will work to debug any Linux kernel regardless of whether systemd is being used.

**Comment by Azaretdodo** [comment]
Thanks you,

Now I understand how the program works I wasn't read more bottom,

I open a new ticket or I answer this ticket if I happen a problem and if this ticket isn't close,

Regards.


Azatetdodo.
________________________________

**Comment by Azaretdodo** [comment]
your program is really broken as the copy paste here : 

```
sudo drgn
[sudo] Mot de passe de dorianrosse : 
drgn 0.0.18 (using Python 3.8.10, elfutils 0.186, with libkdumpfile)
could not get debugging information for:
kernel (could not find vmlinux for 5.13.0-41-generic)
/usr/lib/modules/5.13.0-41-generic/kernel/net/bluetooth/rfcomm/rfcomm.ko (libdwfl error: No DWARF information found)
/usr/lib/modules/5.13.0-41-generic/kernel/crypto/cmac.ko (libdwfl error: No DWARF information found)
/usr/lib/modules/5.13.0-41-generic/kernel/crypto/algif_skcipher.ko (libdwfl error: No DWARF information found)
/usr/lib/modules/5.13.0-41-generic/kernel/crypto/af_alg.ko (libdwfl error: No DWARF information found)
... 109 more
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, offsetof, reinterpret, sizeof
>>> from drgn.helpers.linux import *
>>> for mod in *('struct module',
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/usr/lib/python3.8/codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/usr/lib/python3.8/codeop.py", line 106, in _maybe_compile
    raise err1
  File "/usr/lib/python3.8/codeop.py", line 93, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "/usr/lib/python3.8/codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<console>", line 1
    for mod in *('struct module',
               ^
SyntaxError: invalid syntax
>>> 

```

what should i do ?

thanks you in advance to help myself fully use your program,

Regards.


Azaretdodo.

**Comment by osandov** [comment]
It appears that you didn't have debugging symbols installed here. See https://drgn.readthedocs.io/en/latest/getting_debugging_symbols.html.
