### ISSUE TITLE
Can't find kernel module name when loading symbols

### ISSUE THREAD

**Issue by brenns10** [osandov/drgn#178]
I'm trying to load kernel module debuginfo into drgn, and hitting an error:

```
_drgn.MissingDebugInfoError: could not get debugging information for:
/share/linuxrpm/vmlinux_repo/64/4.14.35-2047.510.5.4.el7uek.x86_64/bnxt_en.ko.debug (could not find kernel module name)
```

You can see the relevant debuginfo ELF file within [this rpm](https://oss.oracle.com/ol7/debuginfo/kernel-uek-debuginfo-4.14.35-2047.510.5.4.el7uek.x86_64.rpm)  (extract using `mkdir /tmp/rpm && cd /tmp/rpm && rpm2cpio $rpm | cpio -ivd` or something similar).

From what I can tell reading `libdrgn/linux_kernel.c`, the strategy for reading a module file is to first try to get a name from the `.modinfo` section, then from the `.gnu_linkonce.this_module` section. My ELF file happens to have both sections:

```
$ eu-readelf -S bnxt_en.ko.debug | grep -E 'Name|modinfo|this_module'
[Nr] Name                 Type         Addr             Off      Size     ES Flags Lk Inf Al
[19] .modinfo             NOBITS       0000000000000000 00000080 00000a71  0 A      0   0  1
[32] .gnu.linkonce.this_module NOBITS       0000000000000000 00000080 00000340  0 WA     0   0 64
[33] .rela.gnu.linkonce.this_module RELA         0000000000000000 003134e8 00000048 24 I     52  32  8
```

But it seems that both are NOBITS, which I believe means that the ELF file contains no data in either of them. Maybe this is a result of how the stripping process works for our packaging (separating the module debuginfo file from the original module itself)?

I'm able to monkey patch this particular ELF file to convince drgn to read it, by adding data into the vacant section using objcopy :fearful: 

```
python -c 'f = open("modinfo.txt", "wb"); f.write(b"name=bnxt_en\0"); f.close()'
objcopy bnxt_en.ko.debug{,.new} --set-section-flags .modinfo=contents --update-section .modinfo=modinfo.txt
```

Which is neat, of course I don't want to be doing that in production. And this does feel a bit silly: the name of the module is in the filename itself. Sure, I could rename it and I suppose that would cause bad things later on in the debuginfo loading, but is there any way we could ask drgn to infer based on the filename?

**Comment by osandov** [comment]
I think @ypl-coffee ran into this before. I think the proper solution for this is to match modules to manually provided files by their build ID, since we can count on that being in the debug-only file unlike the module name. I'm doing that in the debug info discovery rework, but it'd probably be possible to split it out as its own fix.

**Comment by brenns10** [comment]
That makes sense, but I notice that `struct module` only contains a build ID since v5.14, introduced in commit torvalds/linux@9294523e3768 ("module: add printk formats to add module build ID to stacktraces"). It's probably feasible to backport for distribution kernels that want this.

On the other hand, if there were an additional `modules: Dict[str, str]` argument to [`Program.load_debug_info()`](https://drgn.readthedocs.io/en/latest/api_reference.html#drgn.Program.load_debug_info), then we could allow library users (who may know more about the filesystem layout or debuginfo locations) to provide that information even on pre-5.14 kernels.
