### ISSUE TITLE
drgn fails to recognize kernel core dump image

### ISSUE THREAD

**Issue by krisman** [osandov/drgn#182]
I'm experimenting with drgn to debug core dumps collected from qemu dump-guest-memory functionality.  This generates a valid kernel core dump of the guest from the host, which can be examined by crash.  But, when imported into drgn, it seems to think it is debugging a program, and cannot use features of kernel debugging:

--- steps to reproduce:
1) Run qemu vm with QMP:    kvm -qmp tcp:localhost:4444,server,nowait [...]

2) Force a core dump:
```
#!/usr/bin/expect -f

spawn telnet localhost 4444
send "{ \"execute\": \"qmp_capabilities\" }\r"
expect "{\"return\": {}}"
send "{\"execute\":\"dump-guest-memory\",\"arguments\":{\"paging\":true,\"protocol\":\"file:/tmp/vmcore.img\"}}\r"
expect "{\"return\": {}}"
```

3) Load it into drgn:
```
drgn -c /tmp/vmcore.img -s ~/var/build/linux/virtme/vmlinux
```
4) run:

```
>>> from drgn.helpers.linux.pid import *
>>> cmdline(find_task(prog, 1))

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib64/python3.10/site-packages/drgn/helpers/linux/mm.py", line 271, in cmdline
    return access_remote_vm(mm, arg_start, arg_end - arg_start).split(b"\0")[:-1]
  File "/usr/lib64/python3.10/site-packages/drgn/helpers/linux/mm.py", line 251, in access_remote_vm
    return _linux_helper_read_vm(mm.prog_, mm.pgd, address, size)
ValueError: virtual address translation is only available for the Linux kernel
```

I'm not familiar with drgn internals, but it seems it is running against a userspace program, and not a kernel?
The core dump is valid, as shown by crash:

```
$ crash /tmp/vmcore.img  ~/var/build/linux/virtme/vmlinux

     KERNEL: /home/krisman/var/build/linux/virtme/vmlinux
     DUMPFILE: /tmp/vmcore.img
     CPUS: 1
     DATE: Fri Jun 17 19:52:35 EDT 2022
     UPTIME: 00:05:12
     LOAD AVERAGE: 2.85, 1.12, 0.42
     TASKS: 52
     NODENAME: (none)
     RELEASE: 5.19.0-rc1-mingl-ubd
     VERSION: #3 SMP PREEMPT_DYNAMIC Thu Jun 16 18:46:01 EDT 2022
     MACHINE: x86_64  (1896 Mhz)
     MEMORY: 2 GB
     PANIC: ""
     PID: 0
     COMMAND: "swapper/0"
     TASK: ffffffff828149c0  [THREAD_INFO: ffffffff828149c0]
     CPU: 0
     STATE: TASK_RUNNING
     WARNING: panic task not found

crash> task -R comm
PID: 0      TASK: ffffffff828149c0  CPU: 0   COMMAND: "swapper/0"
  comm = "swapper/0\000\000\000\000\000\000",

```
Is there anyway to force drgn to believe this is a kernel dump?

**Comment by osandov** [comment]
Thanks for the report. I'll try to reproduce this, but in the meantime, could you please share the output of `eu-readelf -h -l -n /tmp/vmcore.img`?

**Comment by krisman** [comment]
hi @osandov thanks for the quick reply.  Let me know if you need more information.

you can find the output of eu-readelf here: https://people.collabora.com/~krisman/gh182/vmcore.img.readelf

**Comment by osandov** [comment]
I believe I figured out what's going on here: by default, `dump-guest-memory` doesn't include the necessary metadata for drgn to use the core dump as a Linux kernel core dump (namely, the `VMCOREINFO` note). Luckily, with a little more configuration, QEMU can add the `VMCOREINFO` note to the core dump. You need to:

* Add `-device vmcoreinfo` to your QEMU command line (requires QEMU >= 2.11).
* Compile your kernel with `CONFIG_CRASH_CORE=y` and `CONFIG_FW_CFG=y` or `=m` (requires Linux >= 4.17).
* Load the `qemu_fw_cfg` module if you didn't build it in and it wasn't loaded automatically.

That should make `dump-guest-memory` produce a dump that drgn can work with. I added a check in drgn that will provide that advice if it detects a QEMU guest memory dump without `VMCOREINFO`. I tested this and it worked for me. Please let me know if it fixes the issue for you.

**Comment by krisman** [comment]
@osandov thanks! I confirm the above changes fixes the issue and make drgn recognize my core dump as a kernel dump.  

Closing the issue!

**Comment by brenns10** [comment]
Just wanted to share a few things related to the vmcoreinfo with VM memory dumps.

Even without the hypervisor and linux conspiring together to create the vmcoreinfo note, the kernel still contains it somewhere in memory. It's not fast, but it's totally possible to use strings to dig through the ELF image until you finds something that looks like a vmcoreinfo note. I have a [script](https://gist.github.com/brenns10/b02ef42a1c44afef5aab1eddbd847587) which wraps strings and does just that.

From there, it's a matter of patching up the ELF file and writing a new one. I've written a tool for a similar task in C, but it's only used for inserting additional information into an already created vmcoreinfo note (thus growing the file without messing up the remaining contents). I'd need to clean up and expand that tool to support adding a new vmcoreinfo note to an ELF core dump that doesn't already contain one. If I get around to that, I may create a little repository with my collected tools for patching, searching, updating vmcoreinfo, and they would be very useful in situations like this.

Hyper-V has some related [tools](https://github.com/Azure/azure-linux-utils/tree/master/vm2core/src) which can read a memory dump from their proprietary format and emit it in ELF format. It produces the most wonderfully broken ELF dumps, which contain a fake vmcoreinfo note to "keep crash happy". Thus the need for my tools above :)

**Comment by osandov** [comment]
@brenns10, that's a great point, and a clever tool. If we really wanted to, I suppose that drgn could even search for the VMCOREINFO in the core dump, although it's probably too slow and error-prone to do automatically.

P.S. my tool for dumping `/proc/kcore` to a file (https://github.com/osandov/osandov-linux/blob/master/scripts/kcore_to_vmcore.c) is in the same realm of "useful and relevant to drgn but doesn't have a proper home". There's probably something we can do with those in the future.
