### ISSUE TITLE
Packit failing on Fedora ELN

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#188]
All Fedora ELN builds are failing with something like:

```
ERROR: Command failed: 
 # /usr/bin/dnf --installroot /var/lib/mock/fedora-eln-x86_64-bootstrap-1657124559.712774/root/ --releasever eln --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk --disableplugin=versionlock install dnf dnf-plugins-core --setopt=tsflags=nocontexts --setopt=tsflags=nocontexts --setopt=tsflags=nocontexts
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Copr repository                                  68 kB/s | 3.3 kB     00:00    
Fedora - ELN - Developmental packages for the n 1.5 kB/s | 196  B     00:00    
Errors during downloading metadata for repository 'eln':
  - Status code: 404 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/os/repodata/repomd.xml (IP: 2620:52:3:1:dead:beef:cafe:fed6)
Error: Failed to download metadata for repo 'eln': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

See https://dashboard.packit.dev/results/copr-builds/393591 for an example.

@davide125 any idea what's going on here? Should we just disable these?

**Comment by davide125** [comment]
Probably a bad compose, I'll follow up with upstream and see what's going on there.

**Comment by davide125** [comment]
This is due to the repo layout changing, it will be fixed once https://github.com/rpm-software-management/mock/commit/aa512e124775a43d5ac6e0cfbf8c75a4e2f84eb0 gets into production

**Comment by osandov** [comment]
Looks like we're making it further now, but we're missing `libkdumpfile-devel` on x86-64, aarch64, ppc64le, and s390x:

```
Copr repository                                  62 kB/s | 3.3 kB     00:00    
Fedora - ELN BaseOS - Developmental packages fo  41 kB/s | 2.3 kB     00:00    
Fedora - ELN AppStream - Developmental packages  42 kB/s | 2.3 kB     00:00    
Fedora - ELN CodeReady Linux Builders - Build p  40 kB/s | 2.3 kB     00:00    
No matching package to install: 'libkdumpfile-devel'
Not all dependencies satisfied
Error: Some packages could not be found.
```

Oddly enough, it is available on i386. https://github.com/osandov/drgn/runs/7618388654 has a recent run.

**Comment by michel-slm** [comment]
the i386 build is not for ELN though (ELN, like CentOS Stream, dropped it a long time ago). @davide125 and I suspect it's because the ELN content resolver only resolves runtime deps, and not build requirements, so... libkdumpfile-devel is not published.

We can include libkdumpfile-devel manually now, but we should bring this up at the next ELN meeting, as pulling in only runtime and not build dependencies make managing dependencies much more tedious

**Comment by davide125** [comment]
I put up https://github.com/minimization/content-resolver-input/pull/725 for this.

**Comment by osandov** [comment]
This seems to be fixed now.
