### ISSUE TITLE
[Request] Implement pretty printing support in Jupyter notebook

### ISSUE THREAD

**Issue by shunghsiyu** [osandov/drgn#199]
[Jupyter notebook and drgn](https://twitter.com/omsandov/status/1557822779755442176/photo/1) seems to be a really great combination, it'd would be nice to see pretty printing of drgn object in Jupyter notebook implemented for a even better synergy (similar to what's being done in [interactive mode](https://drgn.readthedocs.io/en/latest/user_guide.html#interactive-mode)).

In theory implementing [`_repr_pretty()`](https://ipython.readthedocs.io/en/stable/config/integrating.html) is all that's needed, something like what [stackoverflow suggests](https://stackoverflow.com/a/41454816), but done with C inside libdrgn/python/object.c.

```python
    def _repr_pretty_(self, p, cycle):
       p.text(str(self) if not cycle else '...')
```

**Comment by osandov** [comment]
I'm closing this one now since your pretty printing support was previously merged. #318 will track further integration.
