### ISSUE TITLE
Packit is failing because COPYING doesn't exist anymore

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#221]
b156d987d7777d27057f56ba62e7f20e3c323ce5 moved drgn's main license file from `COPYING` to `LICENSES` a la FSFE REUSE. (Subsequent commits added the other licenses used in the repository, and then 87b7292aa56a35ca13380f6e18c80832e1c58315 changed the main license.) This is making RPM builds fail at `%license COPYING`. See https://dashboard.packit.dev/results/copr-builds/511047 for an example.

@davide125, @michel-slm, what's the best way to fix this? Should I bring back `COPYING` as a symlink to `LICENSES/LGPL-2.1-or-later.txt`? Should the rpmspec copy the whole `LICENSES` directory instead?

**Comment by davide125** [comment]
Both. We need to update the spec to include the new licenses, and update the license tag accordingly. But you should also add back COPYING (as that's what github uses to infer the project license, among other things) -- I'd probably put a short blurb in it summarizing the project license and pointing folks to the stuff in LICENSES for details.

**Comment by osandov** [comment]
> I'd probably put a short blurb in it summarizing the project license and pointing folks to the stuff in LICENSES for details.

Ah, it looks like that's what Linux has: https://github.com/torvalds/linux/blob/master/COPYING. I'll add that in a sec.

**Comment by osandov** [comment]
Ok, added it back. That should fix Packit, but as you pointed out, the RPM spec still needs updating. I can do that when I get back from PTO if you don't get to it before then.

**Comment by michel-slm** [comment]
libbpf has something more minimal where COPYING is just an SPDX license string, that works too

**Comment by osandov** [comment]
Just cut a release and put up a PR to update the spec: https://src.fedoraproject.org/rpms/python-drgn/pull-request/3
