### ISSUE TITLE
Make object pretty printing more flexible

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#23]
The current `Object.__str__()` implementation has nice defaults for interactive use (e.g., it automatically dereferences pointers, includes the type name, etc.). However, for scripted use, it'd be nice to have more flexibility.

The following is a list of formatting options that I could come up with (* indicates new functionality):
* Include member names when printing structs/unions/classes
* Include indices when printing arrays *
* Dereference pointers
* Format `char []` and `char *` as string literals
* Format `char` as character literals *
* Include type names
* Include zero-initialized members/elements
* "Symbolize" pointers (i.e., include symbol+offset) *

It should be possible to specify these options separately for the top-level object, members, and elements, where applicable (e.g., whether to include type names).

We should define default options (possibly user-defined?) to use for `Object.__str__()`.

There are a couple of options for the interface. One is an `Object.format_()` method that takes flags. E.g.,

```python
print(obj.format_(FormatObjectFlags.DEREFERENCE |
                  FormatObjectFlags.STRING |
                  FormatObjectFlags.STRING_MEMBERS |
                  FormatObjectFlags.STRING_ELEMENTS |
                  FormatObjectFlags.TYPE_NAME |
                  FormatObjectFlags.TYPE_NAME_MEMBERS))

print(obj.format_(prog.default_format_object_flags &
                  ~FormatObjectFlags.DEREFERENCE))
```

Pros:
* Clear semantics

Cons:
* Very verbose
* Not convenient for using default options with some minor modifications

Another option is defining our own format specification syntax via `Object.__format__()` that could then be used via f-strings and `str.format()`. E.g., with a syntax inspired by `chmod`:

```python
# Initial = resets all options, remaining options enable [d]ereference,
# [s]tring, and [t]ype name for the [o]bject, [m]embers, and/or [e]lements.
print(f'{obj:=,d=o,s=ome,t=om}')

# Use the defaults sans the [d]ereference [o]bject flag.
print(f'{obj:d-o}')
# Equivalent:
print('{:d-o}'.format(obj))
print(format(obj, 'd-o'))
```

Pros:
* Much more concise
* Easy to make minor adjustments to default flags

Cons:
* Somewhat opaque syntax

**Comment by ahrens** [comment]
For `sdb`, I think either way would work fine.  I don't think we'd be doing this from very many places in the code, so the verbosity of `.format_()` wouldn't be a big deal (might actually be a pro).

**Comment by osandov** [comment]
The [`format-options`](https://github.com/osandov/drgn/tree/format-options) branch has an interface for this that I'm happier with. For the simple case where you don't want to dereference but otherwise want the default behavior, you can do:

```python
print(obj.format_(dereference=False))
```

The default behavior is mostly the same with one change: pointers are now "symbolized". E.g.,

```python
>>> prog['init_task'].restart_block.fn
(long (*)(struct restart_block *))do_no_restart_syscall+0x0 = 0xffffffff84886d30
```

**Comment by osandov** [comment]
Merged.
