### ISSUE TITLE
Quick Start error，KeyError: 'init_task'

### ISSUE THREAD

**Issue by wangyong5123** [osandov/drgn#231]
~# sudo drgn
drgn 0.0.21+66.g7b64aee (using Python 3.10.6, elfutils 0.186, without libkdumpfile)
could not get debugging information for:
kernel (could not find vmlinux for 5.15.0-56-generic)
kernel modules (could not find loaded kernel modules: could not find 'struct module')
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, offsetof, reinterpret, sizeof
>>> from drgn.helpers.common import *
>>> from drgn.helpers.linux import *
>>> prog['init_task'].comm
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
KeyError: 'init_task'

**Comment by osandov** [comment]
> could not get debugging information for:
> kernel (could not find vmlinux for 5.15.0-56-generic)
> kernel modules (could not find loaded kernel modules: could not find 'struct module')

It looks like you don't have debugging symbols installed. See https://drgn.readthedocs.io/en/latest/getting_debugging_symbols.html.
