### ISSUE TITLE
Support stack traces for kdump files

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#24]
drgn uses the `NT_PRSTATUS` ELF note in core dumps to get the initial registers for stack unwinding. (I think?) kdump files include this note as well, but libkdumpfile doesn't have an interface to get it. It should suffice to add `kdump_prstatus_raw()` to libkdumpfile similar to `kdump_vmcoreinfo_raw()`, although we might want a generic `kdump_note_raw()` instead.

**Comment by sdimitro** [comment]
As mentioned in the meeting I can pick this up!

**Comment by sdimitro** [comment]
This can be closed as https://github.com/osandov/drgn/pull/45 has been merged
