### ISSUE TITLE
Check that vmlinux and kernel modules match core dump/running system

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#25]
Right now, we'll blindly accept the debug info passed by the user. We should sanity check that they match the program we're debugging. This issue is specifically for the kernel; userspace is going to need a different implementation.

Ideally, we should be able to check by build ID. Unfortunately, as far as I can tell, there is no easy way to get the build ID of vmlinux from either `/proc/kcore` or a `vmcore`. We probably want to add the build ID to the `VMCOREINFO` note, but in the mean time we can check `OSRELEASE`. See the discussion in delphix/sdb#41.

I think we can already get the build ID for kernel modules via the sections we get from sysfs or the `modules` variable in the kernel.

As mentioned in the sdb issue, there should also be a way to override these sanity checks and load the debug information anyways.

**Comment by vt-alt** [comment]
There is easy way to determine build-id for the running kernel from `/sys/kernel/notes` which is detached `.notes` section of `vmlinux`. It exists since v2.6.23 (2007). For eample, perf can show it with `perf buildid-list --kernel`.

**Comment by osandov** [comment]
Nice, that works for the live case, thanks! I still haven't found anything for the vmcore case, which might be more important since it's more likely that you'll find the wrong kernel if you're debugging a vmcore from another machine.

**Comment by vt-alt** [comment]
Btw, sorry for a slight off-topic, what do you think, should Linux show GNU build-ids on stack traces?

**Comment by osandov** [comment]
It looks like the build ID was added to `VMCOREINFO` in Linux 5.9 (torvalds/linux@0935288c6e008c0682ab6171fb5605dcc049e7bd). We should use that now.

**Comment by osandov** [comment]
@vt-alt sorry I missed your other question before! I do think drgn needs an API for getting the debug info module (and corresponding build ID) that a symbol came from. I don't have concrete plans for that quite yet, though.

**Comment by brenns10** [comment]
@osandov do you happen to know, is this bug still valid for the latest drgn? I recall we now match modules by build ID rather than name, which means that mismatched modules may get loaded at address 0. But from what I've observed, drgn still loads vmlinux regardless of mismatched build ID. Is that accurate?

**Comment by osandov** [comment]
Yup, that's all correct at the moment. My (perpetual) rework of this area will fix this.
