### ISSUE TITLE
vmtest.vm: failing tests when run locally

### ISSUE THREAD

**Issue by marxin** [osandov/drgn#266]
I see the following failures when I run `vmtest.vm` locally:

```
$ python3 -m vmtest.vm -k '6.2.*' python3 -Bm pytest
...
FAILED tests/test_dwarf.py::TestTypes::test_explicit_global_namespace - SyntaxError: invalid character \x3a
FAILED tests/test_dwarf.py::TestTypes::test_namespaces - SyntaxError: invalid character \x3a
FAILED tests/test_dwarf.py::TestTypes::test_template_in_namespace - SyntaxError: invalid character \x3a
FAILED tests/linux_kernel/helpers/test_common.py::TestPrintAnnotatedStack::test_print_annotated_stack - KeyError: 'drgn_test_slob'
```

**Comment by osandov** [comment]
https://github.com/osandov/drgn/commit/b05e02d4ec8d8df5f96f11cc005ca821ca7e96f0 should fix that last error. For the errors in `test_dwarf.py`, my guess is that you need to rebuild drgn to get the changes from https://github.com/osandov/drgn/commit/7e6efe6649c25a167b8ff956cfeb5cf916c909bd.

`python3 setup.py test -k '6.2.*'` will automatically rebuild drgn and run tests in the VM, including building a test kernel module for some helpers. https://github.com/osandov/drgn/tree/main/vmtest has some more information.

**Comment by marxin** [comment]
Great, that works for me! Thank you.
