### ISSUE TITLE
Help: could not find loaded kernel modules

### ISSUE THREAD

**Issue by tzssangglass** [osandov/drgn#290]
Hi, I build drgn from source and it works really well, thank you.

When I run `sudo drgn`, I found an error reporting that

```shell
warning: could not get debugging information for:
kernel modules (could not find loaded kernel modules: address is not mapped: 0xfffffffffffffff8)
```

I would like to know how to fix it.

my OS version:

```
uname -a
Linux ubuntu 5.19.0-37-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Wed Mar 1 18:08:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

maybe useful

```
cat /boot/config-5.19.0-37-generic | grep CONFIG_RANDOMIZE_BASE
CONFIG_RANDOMIZE_BASE=y
```

drgn version
```
sudo drgn --version
drgn 0.0.22+unknown (using Python 3.10.6, elfutils 0.186, with libkdumpfile)
```

**Comment by osandov** [comment]
Hi, sorry I missed this issue before. Are you still able to reproduce it?

**Comment by tzssangglass** [comment]
Hi @osandov 

I built drgn with the main branch again and tested it again, it works, so we can close this issue, thank you.

**Comment by osandov** [comment]
Thank you for checking!
