### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [osandov/drgn#3]
I would like to point out that an identifier like “[`___PASTE`](https://github.com/osandov/drgn/blob/75c3679147a513dc2114324ae80c945766a3d4de/libdrgn/internal.h#L70 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by osandov** [comment]
These are copied from the Linux kernel, so no, I'd rather be consistent with the original.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
