### ISSUE TITLE
'ValueError: not an ELF core file' error on ubuntu

### ISSUE THREAD

**Issue by mishuang2017** [osandov/drgn#344]
It works for live kernel, but it doesn't work for dump file. Maybe it is because the dump file is compressed.

`>>> drgn.program_from_core_dump("/var/crash/202308101309/dump.202308101309")
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
ValueError: not an ELF core file
>>>
# file dump.202308101309
dump.202308101309: data`

Any suggestion? Thanks.

**Comment by osandov** [comment]
drgn supports ELF core dumps and kdump compressed dumps. How was this core dump generated and compressed? The usual tool is makedumpfile, which looks something like this:

```console
# makedumpfile /proc/vmcore core
...
# file core
core: Kdump compressed dump v6, system Linux, node vmtest, release 6.5.0-rc5-vmtest21.1default, version #1 SMP PREEMPT_DYNAMIC Mon Aug  7 06:45:13 UTC 2023, machine x86_64, domain (none)
# xxd core | head
00000000: 4b44 554d 5020 2020 0600 0000 4c69 6e75  KDUMP   ....Linu
00000010: 7800 0000 0000 0000 0000 0000 0000 0000  x...............
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0076 6d74  .............vmt
00000050: 6573 7400 0000 0000 0000 0000 0000 0000  est.............
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 362e  ..............6.
00000090: 352e 302d 7263 352d 766d 7465 7374 3231  5.0-rc5-vmtest21
```

Could you please provide the output of `xxd dump.202308101309 | head`?

**Comment by mishuang2017** [comment]
`# xxd dmesg.202308101309 | head
00000000: 6d61 6b65 6475 6d70 6669 6c65 0000 0000  makedumpfile....
00000010: 0000 0000 0000 0001 0000 0000 0000 0001  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................`

The kdump on fedora looks like this:

`$ file vmcore
vmcore: Kdump compressed dump v6, system Linux, node c-237-115-160-163, release 6.5.0-rc2+, version #2 SMP PREEMPT_DYNAMIC Tue Jul 25 09:55:12 IDT 2023, machine x86_64, domain lab.mtl.com
$ xxd vmcore | head
00000000: 4b44 554d 5020 2020 0600 0000 4c69 6e75  KDUMP   ....Linu
00000010: 7800 0000 0000 0000 0000 0000 0000 0000  x...............
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0063 2d32  .............c-2
00000050: 3337 2d31 3135 2d31 3630 2d31 3633 0000  37-115-160-163..
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 362e  ..............6.
00000090: 352e 302d 7263 322b 0000 0000 0000 0000  5.0-rc2+.......`

So it seems like kdump was not generated successfully. I'll check why. Thanks a lot for the quick reply.

**Comment by brenns10** [comment]
Reformatting this for you:

```
# xxd dmesg.202308101309 | head
00000000: 6d61 6b65 6475 6d70 6669 6c65 0000 0000  makedumpfile....
00000010: 0000 0000 0000 0001 0000 0000 0000 0001  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

This isn't a corrupted file, it's a core dump in the "flattened format" of makedumpfile. Something I learned about [here](https://lore.kernel.org/linux-debuggers/87o7qpngka.fsf@oracle.com/T/#t). Try using `makedumpfile -R` on it, and then using drgn to open the resulting file.

**Comment by osandov** [comment]
Good catch, thanks @brenns10! I wonder if we can check for the flat format header in `drgn_program_set_core_dump()` and give the user some guidance.

**Comment by brenns10** [comment]
Yeah, that's a good idea.

Crash is actually capable of reading a flat file directly. Not libkdumpfile though.

The flat format is basically just a bunch of instructions on how to create the final file, each in the form of "seek to offset X, and then write the following Y bytes". This means it's not terribly difficult to read the file and index it so that you can allow random access, I suspect that's what Crash does. Unfortunately, the indexing takes a while and it needs to be redone each time you start a new crash session... So in my opinion, while it's nice that Crash reads them, I'd actually prefer that it just tell me how to fix the file so I don't have to wait a long time for it!

So I think detection and providing a descriptive error message is the better move here.

**Comment by mishuang2017** [comment]
@brenns10 Thanks a lot! I need to run the following command to rearrange the dump file:

`# cat dump.202308100123 | makedumpfile-R.pl ../vmcore.1
Start re-arranging dump data of flattened format to a dumpfile.
The dumpfile is saved to ../vmcore.1.
Completed.`

But I still don't know how to reformat above code :(

**Comment by brenns10** [comment]
Does drgn load the resulting reassembled core dump?

> But I still don't know how to reformat above code :(

If you mean formatting the code block in markdown so it displays properly, you should use the triple backtick code block syntax, also called "fenced":

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by mishuang2017** [comment]
@brenns10 
```
drgn can load the reassembled core dump after running makedumpfile.
Formating the code also works.
Thank you very much.
```
