### ISSUE TITLE
Add helper for getting kernel CONFIG options

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#36]
If the kernel was compiled with `CONFIG_IKCONFIG=y`, then the gzipped kernel configuration exists in kernel memory (see [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/configs.c?h=v5.5-rc5)). We can't access it currently:

```
>>> prog.variable('kernel_config_data')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
LookupError: could not find variable 'kernel_config_data'
```

This is because `kernel_config_data` and `kernel_config_end` are defined in assembly. We'll need to add an interface for looking up ELF symbols by name.

**Comment by osandov** [comment]
This entails:

* Adding `drgn_program_find_symbol_by_name()` to `libdrgn`.
  * Code is in `libdrgn/program.c`.
  * This will need to iterate over each "module" (executable or library file, essentially) with `dwfl_getmodules()` and then iterate through the symbol table of each module (`dwfl_module_getsymtab()`, `dwfl_module_getsymtab_first_global()`) looking for a match with the given name (`dwfl_module_getsym_info()`).
* Maybe renaming `drgn_program_find_symbol()` to `drgn_program_find_symbol_by_address()` for clarity (the `libdrgn` API is subject to change so this would be fine).
* Allowing `prog.symbol()` in the Python bindings to take a `str` in addition to an `int`.
  * The code is in `libdrgn/python/program.c` and the documentation is in `docs/api_reference.rst`.
* Adding a Python helper (`kconfig()`?) that takes the program and returns a dictionary mapping option names to 'y' or 'm'.
  * Add to a new `drgn/helpers/linux/kconfig.py` file.
  * Look up the `kernel_config_{data,end}` symbols, read the raw data, decompress it, and parse it. We probably want to cache it in `prog.cache` so we don't redo this every time we call `kconfig()`.

**Comment by jgkamat** [comment]
Thanks for the detailed breakdown! I'll be working on this over the next couple days :)
