### ISSUE TITLE
Smoke testing on other architectures

### ISSUE THREAD

**Issue by vt-alt** [osandov/drgn#373]
I want to add smoke tests when building `drgn` for ALT Linux. I decided to run `contrib/kernel_sys.py` and `contrib/platform_drivers.py`. I just want to be sure this is correct approach. So the questions are:

- Everything fails on ARM32 with `[Errno 2] No such file or directory: '/proc/kcore'` -- is this expected? It seems there is no `kcore` on ARM32 -- `linux/fs/proc/Kconfig` have:
```
config PROC_KCORE
        bool "/proc/kcore support" if !ARM
        depends on PROC_FS && MMU
        select CRASH_CORE
```
- `platform_drivers.py` fails on ppc64le with 
```
 ++ drgn /usr/share/drgn/contrib/platform_drivers.py
 reg-dummy
 Traceback (most recent call last):
   File "/usr/bin/drgn", line 9, in <module>
     sys.exit(_main())
              ^^^^^^^
   File "/usr/lib64/python3/site-packages/drgn/cli.py", line 301, in _main
     runpy.run_path(script, init_globals={"prog": prog}, run_name="__main__")
   File "<frozen runpy>", line 291, in run_path
   File "<frozen runpy>", line 98, in _run_module_code
   File "<frozen runpy>", line 88, in _run_code
   File "/usr/share/drgn/contrib/platform_drivers.py", line 28, in <module>
     print(platform_driver)
 Exception: virtual address translation is only supported for Radix MMU
```
is this ok too?
- Or maybe you would suggest better smoke testing?

Thanks,

**Comment by osandov** [comment]
For ARM32, yes, that's unfortunately expected. I apply a patch to enable `/proc/kcore` for the kernels that I use to test drgn: https://github.com/osandov/drgn/blob/main/vmtest/patches/proc-kcore-allow-enabling-CONFIG_PROC_KCORE-on-ARM.patch. I haven't gotten around to sending it upstream.

I'm not sure what's going on with ppc64le there. Do other scripts (maybe `contrib/lsmod.py` or `contrib/mount.py`) have the same issue? What ppc64 system is that running on?

For what it's worth, the scripts in `contrib` have no guarantees; they might disappear in new drgn releases, or break for new kernel releases. If you don't want to run the full test suite, it might be best for ALT Linux to have its own test script that runs a a few important helpers.

**Comment by vt-alt** [comment]
1. I run test suite but only under `builder` user, since in our build system (rpmbuild based) it's impossible to bring `debuginfo` for the kernel while building. (To run it properly I would need to separate drgn testsuite into independent package (like I do for these smoke tests), then run it in vm, but I'm not sure it's [easily] possible.)
2. `contrib/lsmod.py` does not work too:
```
root@powerpc64le:/usr/share/drgn/contrib# ./lsmod.py
Module                  Size  Used by
Traceback (most recent call last):
  File "/usr/bin/drgn", line 9, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/usr/lib64/python3/site-packages/drgn/cli.py", line 301, in _main
    runpy.run_path(script, init_globals={"prog": prog}, run_name="__main__")
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "./lsmod.py", line 13, in <module>
    size = (mod.init_layout.size + mod.core_layout.size).value_()
            ^^^^^^^^^^^^^^^
AttributeError: 'struct module' has no member 'init_layout'
```
3. `ps.py`, `vmmap.py`, `vmstat.py`, `kcore_list.py`, `mount.py` - they seem to work good.
4. I run them under Linux v6.6.4 guest vm (under qemu-kvm) on v6.1.37 host. It's POWER8. `lscpu` excerpt:
```
Architecture:            ppc64le
  Byte Order:            Little Endian
Model name:              POWER8 (architected), altivec supported
  Model:                 2.0 (pvr 004d 0200)
```
Maybe this ppc issue is not that important since other things are working. (These (including arm32) architectures aren't my main priority but I would like to inform you about the issues.)

**Comment by osandov** [comment]
(Apologies for the late response.) I just fixed that `lsmod.py` error. The arm32 issue is a known limitation, so I'm going to go ahead and close this. Feel free to reopen.
