### ISSUE TITLE
Stop generating drgn.h

### ISSUE THREAD

**Issue by pcc** [osandov/drgn#375]
I use [Bear](https://github.com/rizsotto/Bear) to generate a `compile_commands.json` for drgn so that code navigation (go-to-definition etc) works in my text editor. One issue is that if I navigate to `drgn.h` I end up going to the generated `drgn.h` in my build directory instead of the `drgn.h.in` file that I actually want to edit.

It looks like the only reason why `drgn.h` is generated is to substitute a version number. But these version numbers don't appear to be used by anything in the tree. So I have this local hack:
```
diff --git a/libdrgn/Makefile.am b/libdrgn/Makefile.am
index bbd65cb..8e40b99 100644
--- a/libdrgn/Makefile.am
+++ b/libdrgn/Makefile.am
@@ -129,11 +129,7 @@ c_keywords.inc: build-aux/gen_c_keywords_inc_strswitch.py build-aux/gen_strswitc
        $(AM_V_GEN)$(PYTHON) $< | $(PYTHON) $(word 2, $^) -o $@ -

 drgn.h: drgn.h.in configure.ac
-       $(AM_V_GEN)sed \
-               -e 's/@DRGN_VERSION_MAJOR@/$(word 1,$(subst ., ,@PACKAGE_VERSION@))/g' \
-               -e 's/@DRGN_VERSION_MINOR@/$(word 2,$(subst ., ,@PACKAGE_VERSION@))/g' \
-               -e 's/@DRGN_VERSION_PATCH@/$(word 3,$(subst ., ,@PACKAGE_VERSION@))/g' \
-               $< > $@
+       ln -sf $< $@

 drgn_section_name_to_index.inc: build-aux/gen_elf_sections.py build-aux/gen_strswitch.py build-aux/codegen_utils.py
        $(AM_V_GEN)$(PYTHON) $< | $(PYTHON) $(word 2, $^) -o $@ -
```
which improves the situation somewhat (code navigation to `drgn.h.in` works), but my text editor does not recognize `drgn.h.in` as a C file, so navigation away from `drgn.h.in` doesn't work.

It seems the easiest fix would be to remove the `DRGN_VERSION_*` definitions and make `drgn.h` non-generated, which we would be allowed to do because the documentation states that `drgn.h` is not a stable API, but this presumably wouldn't be friendly towards C API users (are there any?) A couple of other options would be to move them to a separate generated header file like `drgn_version.h` which would be included from `drgn.h`, or to do the version substitution on the installed version of the header rather than the one in the build directory.

**Comment by osandov** [comment]
This has been bugging me, too. I played around with doing some magic with autoconf, but it doesn't seem worth the trouble. I'll just hard-code the version in two places (configure.ac and drgn.h) for now.

**Comment by pcc** [comment]
Thanks!
