### ISSUE TITLE
Remove scalar restriction on reinterpret

### ISSUE THREAD

**Issue by pcc** [osandov/drgn#378]
The documentation for `reinterpret` states:
```
    However, value objects with a scalar type
    cannot be reinterpreted, as their memory layout in the program is not
    known.
```
I don't understand this restriction. As long as the program endianness is known (which it usually is), it should be possible to produce a buffer containing a value of the scalar type with the target endianness, and then reinterpret in the same way as we are already doing for buffers.

**Comment by osandov** [comment]
You're right, there's no reason this can't be supported. Bit fields and big endian probably have some tricky corner cases, but nothing insurmountable. I'll take a look.
