### ISSUE TITLE
C struct bitfield formatting depends on order of construction

### ISSUE THREAD

**Issue by brenns10** [osandov/drgn#386]
Here's an observation -- but I'm actually leaning toward it not being a bug. I just wanted to share this oddity.

When constructing C structs with bitfields, different versions of CTF may present the bitfield members in different orders. They may not be in the same order as the original declaration.

For instance, the `struct desc_struct` on x86 Linux is a good example. It is declared as follows:

```
struct desc_struct {
	u16	limit0;
	u16	base0;
	u16	base1: 8, type: 4, s: 1, dpl: 2, p: 1;
	u16	limit1: 4, avl: 1, l: 1, d: 1, g: 1, base2: 8;
} __attribute__((packed));
```

Take the `base1` field. It should be at bit offset 32, and it is declared 3rd in declaration order. The DWARF type is properly handled in drgn, showing the correct offset and the order is correct.

```
>>> prog.type("struct desc_struct")
struct desc_struct {
        u16 limit0;
        u16 base0;
        u16 base1 : 8;
        u16 type : 4;
        u16 s : 1;
        u16 dpl : 2;
        u16 p : 1;
        u16 limit1 : 4;
        u16 avl : 1;
        u16 l : 1;
        u16 d : 1;
        u16 g : 1;
        u16 base2 : 8;
}
>>> prog.type("struct desc_struct").member("base1")
TypeMember(Object(prog, 'u16', bit_field_size=8), name='base1', bit_offset=32)
```

Strangely, CTF may represent this in two ways:

```
struct desc_struct {
        u16 limit0;
        u16 base0;
        u16 p : 1;
        u16 dpl : 2;
        u16 s : 1;
        u16 type : 4;
        u16 base1 : 8;
        u16 base2 : 8;
        u16 g : 1;
        u16 d : 1;
        u16 l : 1;
        u16 avl : 1;
        u16 limit1 : 4;
}
TypeMember(Object(prog, 'u16', bit_field_size=8), name='base1', bit_offset=32)
```

OR:

```
struct desc_struct {
        u16 limit0;
        u16 base0;
        u16 base1 : 8;
        u16 type : 4;
        u16 s : 1;
        u16 dpl : 2;
        u16 p : 1;
        u16 limit1 : 4;
        u16 avl : 1;
        u16 l : 1;
        u16 d : 1;
        u16 g : 1;
        u16 base2 : 8;
}
TypeMember(Object(prog, 'u16', bit_field_size=8), name='base1', bit_offset=32)
```

In either case, the order in which CTF presents the members seems unrelated to the bit offset and bit size. And of course, the C standard makes no guarantee on the ordering of bitfield members. So I guess there's no bug in CTF or drgn. Both representations are valid, so long as the underlying bit offsets and sizes are correct. But is interesting, so I thought I'd share this.

**Comment by brenns10** [comment]
Feel free to close this once you read it, I just wanted it written somewhere :)

**Comment by osandov** [comment]
The DWARF 5 spec section 5.7.1, page 114, lines 8-11, says:

> The members of a structure, union, or class are represented by debugging information entries that are owned by the corresponding structure type, union type, or class type entry and appear in the same order as the corresponding declarations in the source program.

So at least for DWARF, the order is required to be like in your first example. I don't see any such requirement in the [CTF spec](https://raw.githubusercontent.com/wiki/oracle/binutils-gdb/files/ctf-spec.pdf), so maybe this isn't wrong per the spec, but the inconsistency is a bummer.

(Side note, the declaration order can be different from the offset order, for example, for `__randomize_layout` and [Rust](https://lore.kernel.org/lkml/Y+atpJV5rqo08dQJ@kernel.org/)).
