### ISSUE TITLE
Suggestion: pull extended LTS 4.14 from OpenELA

### ISSUE THREAD

**Issue by brenns10** [osandov/drgn#390]
I wanted to suggest this & get feedback before actually sending a pull request for it.

I know that 4.14 is likely on the chopping block _soon-ish_ for the vmtest kernels, since the upstream LTS releases have stopped. However, OpenELA has taken up extended maintenance of the 4.14.y branch using the same processes as the upstream stable tree. It's not tied to any specific distro or vendor, just a continuation of the 4.14.y branch.

https://github.com/openela/kernel-lts/releases
https://github.com/openela/kernel-lts/tree/linux-4.14.y

It probably doesn't matter much to get any new bug fixes for the purposes of vmtest, but if anybody out there is still running a 4.14 kernel, they will likely be taking updates from this branch.

**Comment by osandov** [comment]
I'm leaning towards waiting to see how much adoption this kernel gets. The last 4.14 release can still be built, and I'd be surprised if the extended LTS branch causes any breakages that aren't also caught by a newer stable branch. I'm not in a rush to drop 4.14 even being EOL.

**Comment by brenns10** [comment]
Makes total sense!
