### ISSUE TITLE
Add helpers for page table walking and userspace memory access

### ISSUE THREAD

**Issue by nkaretnikov** [osandov/drgn#53]
For example, is there a way to read from addresses in `task.mm`?

```
# drgn -k -s /usr/lib/debug/boot/vmlinux-5.3.0-42-generic --no-default-symbols
>>> for task in for_each_task(prog):
...   prog.read(task.mm.arg_start, task.mm.arg_end - task.mm.arg_start)
...
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
_drgn.FaultError: could not find memory segment: 0x7ffdc3780ef7
```

**Comment by nkaretnikov** [comment]
I've had similar issues related to address translation when running on dumps too. Those were fixed by using drgn with libkdumpfile (on dumps that it supported).

I'll try using drgn with libkdumpfile on `/proc/kcore` and report back.

**Comment by nkaretnikov** [comment]
Another example:

```
# drgn -k -s /usr/lib/debug/boot/vmlinux-5.3.0-42-generic
drgn 0.0.3 (using Python 3.7.5, without libkdumpfile)
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, reinterpret, sizeof
>>> from drgn.helpers.linux import *
>>>
>>> from drgn.helpers.linux.pid import find_task
>>> from drgn.helpers.linux.fs import d_path
>>>
>>> task = find_task(prog, 1)
>>> vma = task.mm.mmap
>>> while vma:
...   print(d_path(vma.vm_file.f_path))
...   vma = vma.vm_next
...
b'/usr/lib/systemd/systemd'
b'/usr/lib/systemd/systemd'
b'/usr/lib/systemd/systemd'
b'/usr/lib/systemd/systemd'
b'/usr/lib/systemd/systemd'
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/drgn/helpers/linux/fs.py", line 139, in d_path
    dentry = path_or_vfsmnt.dentry.read_()
_drgn.FaultError: could not find memory segment: 0x18
```

```
# ls -l /proc/1/map_files/ | head -n10
total 0
lr-------- 1 root root 64 Mar 23 17:59 5643fcc71000-5643fcca0000 -> /usr/lib/systemd/systemd
lr-------- 1 root root 64 Mar 23 17:59 5643fcca0000-5643fcd4e000 -> /usr/lib/systemd/systemd
lr-------- 1 root root 64 Mar 23 17:59 5643fcd4e000-5643fcd9e000 -> /usr/lib/systemd/systemd
lr-------- 1 root root 64 Mar 23 17:59 5643fcd9f000-5643fcddf000 -> /usr/lib/systemd/systemd
lr-------- 1 root root 64 Mar 23 17:59 5643fcddf000-5643fcde0000 -> /usr/lib/systemd/systemd
lr-------- 1 root root 64 Mar 23 17:59 7f79250e6000-7f79250f5000 -> /usr/lib/x86_64-linux-gnu/libm-2.30.so
lr-------- 1 root root 64 Mar 23 17:59 7f79250f5000-7f792519c000 -> /usr/lib/x86_64-linux-gnu/libm-2.30.so
lr-------- 1 root root 64 Mar 23 17:59 7f792519c000-7f7925233000 -> /usr/lib/x86_64-linux-gnu/libm-2.30.so
lr-------- 1 root root 64 Mar 23 17:59 7f7925233000-7f7925234000 -> /usr/lib/x86_64-linux-gnu/libm-2.30.so

```

**Comment by osandov** [comment]
Hey, thanks for the report!

There are a few separate issues here:

1. For your original question, `task.mm.arg_start` and friends are userspace addresses. E.g., 0x7ffdc3780ef7 isn't meaningful in the kernel, only in the context of the userspace task it came from (and that address might exist in other tasks, too). This means that drgn can't access them directly (just as the kernel itself usually needs to access them through special functions).
However, it is possible to read from userspace memory by walking the task's page table. I have a prototype [here](https://gist.github.com/osandov/f8262082dc27c3a7b744a395be3f3671) which will eventually find its way into drgn.
2. Your observation that libkdumpfile fixed some of these issues is somewhat related. vmcore dumps exclude certain kernel address mappings. This means that they can only be accessed by, again, walking the page table, which libkdumpfile knows how to do. See b05cc0eb751e2fa2ff7d53086946d55f8ae05147. When drgn learns how to walk page tables itself, libkdumpfile won't be necessary for reading vmcores anymore.
3. The vma fault is unrelated. Some vmas (e.g., anonymous mappings) have `vma->vm_file == NULL`. You want
```python
task = find_task(prog, 1)
vma = task.mm.mmap
while vma:
    if vma.vm_file:
        print(d_path(vma.vm_file.f_path))
    vma = vma.vm_next
```

I'll retitle this to reflect the action item: drgn needs helpers for walking page tables and accessing userspace memory.

**Comment by nkaretnikov** [comment]
@osandov Thanks for the quick reply!

Can this be implemented such that the user won't have to do anything special when performing reads/derefs/accessing members?

Given an address (in kernel or userspace), is it possible to know how to translate it? It seems that you can deduce that if the address is above/below a certain value, but I'm not sure if it applies in all cases.

**Comment by osandov** [comment]
I don't think it'd be possible to do this automatically in general. Usually we can easily distinguish between kernel addresses and userspace addresses, but not always. See this [LWN article](https://lwn.net/Articles/781283/). Even when we can distinguish kernel vs userspace address, drgn doesn't know which userspace task you want.

However, drgn is flexible enough that you can do this explicitly. If there's a particular task you're working with, you can add a memory segment that uses the prototype I previously linked:

```python
def add_userspace_memory(task):
    prog = task.prog_
    def read_userspace_memory(address, count, offset, physical):
        return access_remote_vm(task.mm, address, count)
    prog.add_memory_segment(0, task.thread.addr_limit.seg, read_userspace_memory)
```

```python
>>> task = find_task(prog, 1)
>>> add_userspace_memory(task)
>>> cast('char *', task.mm.arg_start)
(char *)0x7fff7409bfa1 = "/usr/lib/systemd/systemd"
```

This uses `task.thread.addr_limit.seg` to distinguish between userspace and kernel addresses, which won't work with some memory layouts like 4G:4G on x86, but it should be okay on x86-64.

**Comment by osandov** [comment]
What stack trace do you get with `while vma`? Could you print out the vma that's causing problems? Something like

```python
task = find_task(prog, 1)
vma = task.mm.mmap
while True:
    try:
        if vma.vm_file:
            print(d_path(vma.vm_file.f_path))
        vma = vma.vm_next
    except FaultError:
        print(vma)
        break
```

**Comment by nkaretnikov** [comment]
(I'll reply to the questions above sometime later, sorry!)

Here's a related issue I'd like to report before I forget: `add_memory_segment` doesn't seem to add any segments when used with `physical=True`, which I verified by using the patch below.

If instead you attempt to add a segment using a physical range (by parsing segments yourself) with `physical=False`, drgn gets confused (of course!). The addresses loaded via `load_debug_info` are virtual (but drgn also subtracts the start of the .text from them for some reason). So any memory access leads to a fault.

I tried working around that by doing address translation in `read_fn`, but that didn't quite work. It went to a point where I had to fake drgn `Object` and `Program` classes to fixup addresses there (on `.variable` accesses) and memory accesses (`.value_`). But even that didn't quite work because some of the helpers use `container_of`, which I cannot hook easily without messing with Python bytecode/modifying memory directly, I think. So that's where I pretty much gave up on this approach as I didn't want to patch drgn itself. I hope I can still use libkdumpfile for my usecase...

```
diff --git a/libdrgn/memory_reader.c b/libdrgn/memory_reader.c
index b368fb8..e63d84e 100644
--- a/libdrgn/memory_reader.c
+++ b/libdrgn/memory_reader.c
@@ -1,6 +1,7 @@
 // Copyright 2018-2019 - Omar Sandoval
 // SPDX-License-Identifier: GPL-3.0+
 
+#include <stdio.h>
 #include <inttypes.h>
 #include <string.h>
 #include <unistd.h>
@@ -227,9 +228,29 @@ struct drgn_error *drgn_memory_reader_read(struct drgn_memory_reader *reader,
 					   void *buf, uint64_t address,
 					   size_t count, bool physical)
 {
+	printf("XXX: physical: %d\n", physical);
+	printf("XXX: address: 0x%lx\n", address);
 	struct drgn_memory_segment_tree *tree = (physical ?
 						 &reader->physical_segments :
 						 &reader->virtual_segments);
+
+	// XXX: Debug.
+	printf("XXX: iterating over the tree\n");
+	struct drgn_memory_segment_tree_iterator it;
+
+	it = drgn_memory_segment_tree_first_post_order(tree);
+	while (it.entry) {
+		struct drgn_memory_segment *entry = it.entry;
+
+		printf("XXX: entry->address: 0x%lx\n", entry->address);
+		printf("XXX: entry->size: 0x%lx\n", entry->size);
+		printf("XXX: entry->orig_address: 0x%lx\n", entry->orig_address);
+
+		it = drgn_memory_segment_tree_next_post_order(it);
+	}
+	printf("XXX: done iterating\n");
+	// XXX: Debug end.
+
 	struct drgn_error *err;
 	size_t read = 0;
 
@@ -239,6 +260,14 @@ struct drgn_error *drgn_memory_reader_read(struct drgn_memory_reader *reader,
 
 		segment = drgn_memory_segment_tree_search_le(tree,
 							     &address).entry;
+
+		if (!segment) {
+			printf("XXX: segment is NULL\n");
+		} else {
+			printf("XXX: segment->address: 0x%lx\n", segment->address);
+			printf("XXX: segment->size: 0x%lx\n", segment->size);
+		}
+
 		if (!segment || segment->address + segment->size <= address) {
 			return drgn_error_create_fault("could not find memory segment",
 						       address);
```

**Comment by osandov** [comment]
Interesting, do you have a reproducer for what you were trying to do that adding physical segments didn't work? I'd be interested to see the script you were running and the output you got from your patch.

**Comment by nkaretnikov** [comment]
Apologies for the delayed response...

> What stack trace do you get with while vma? Could you print out the vma that's causing problems?

Hmm, I cannot reproduce that error now. Note that I had to reinstall drgn and the current version is built with libkdumpfile while the one I used before was built without it, so maybe that's why.

> Interesting, do you have a reproducer for what you were trying to do that adding physical segments didn't work? I'd be interested to see the script you were running and the output you got from your patch.

Cannot share the code or image because that's proprietary, sorry! A bit fuzzy on the details, but IIRC: 
- generated an ELF core with makedumpfile (use `MAKEDUMP_ARGS="-E -d 31"` in `/etc/default/kdump-tools`)
- parsed the ELF core (I used pyelftools) and got a list of segments (physical ranges and data)
- tried to use `add_memory_segment` with `physical=True`
- nothing was printed between `iterating over the tree` and `done iterating` (if you change to `physical=False` the output should change)
- trying to read from a physical address that's supposed to be in one of the physical ranges failed too.

HTH!

BTW: Any estimation on when the kernel/userspace virtual address translation stuff lands? No pressure, just hoping you continue improving the library. I think it's a very useful and easy to use tool, easy to get started with too! Thanks for working on this and making the code available!

**Comment by nkaretnikov** [comment]
@osandov BTW, you can also use Comae DumpItForLinux to get an ELF core more easily. That's what I actually use. I mentioned makedumpfile earlier just because it's a standard tool.

See here for an example on how to run it on AWS, for instance:
https://help.comae.com/linux/aws/

To run locally:
```
$ sudo docker run --privileged -it -v $(pwd):/devel --entrypoint=/bin/sh comaeio/dumpit-linux

/dump # python3 /app/comae-cli/python/comae.py --help 
...
/dump # python3 /app/comae-cli/python/comae.py --dump-it --action store
...
/dump # ls
5.3.0-42-generic.20200407-211609.dumpit.core.zip
/dump # mv 5.3.0-42-generic.20200407-211609.dumpit.core.zip /devel/
/dump # exit
```

You then need to get symbols for your kernel to use crash or drgn.

```
$ crash /usr/lib/debug/boot/vmlinux-5.3.0-42-generic 5.3.0-42-generic.20200407-211609.dumpit.core
crash> lsmod
...
crash> ps
...
```

```
$ DRGN_USE_LIBKDUMPFILE_FOR_ELF=1 drgn -s /usr/lib/debug/boot/vmlinux-5.3.0-42-generic -c 5.3.0-42-generic.20200407-211609.dumpit.core --no-default-symbols /drgn/examples/linux/ps.py
...
```

**Comment by osandov** [comment]
I just pushed the page table walking functionality and the [`access_process_vm()`](https://drgn.readthedocs.io/en/latest/helpers.html#drgn.helpers.linux.mm.access_process_vm) helper which can read from the memory of any task. I also added page table address translation for ELF vmcores, so libkdumpfile is no longer needed for ELF cores.

**Comment by nkaretnikov** [comment]
@osandov Awesome! Thank you so much! Not sure when I'm able to test this, but I'll let you know if I find any issues.
