### ISSUE TITLE
manylinux wheels

### ISSUE THREAD

**Issue by brenns10** [osandov/drgn#68]
Hello again,

I've written some scripts which generate manylinux2010 wheels for drgn. These wheels require no compilation to install, and they bundle the dependencies (such as libkdumpfile) so that it is quite easy to install on any reasonably recent Linux distro (tested on RHEL/OL6+, Ubuntu 20.04).

Among my coworkers, the difficulty to build and install drgn plus libkdumpfile hinders adoption. Especially on older systems such as RHEL/OL 6/7, due to older compiler versions, etc. I think that distributing wheels might simplify installation enough to encourage new users to try out drgn and lower the bar to entry from Crash. Both libkdumpfile and drgn are GPLv3, so there shouldn't be any license concerns with wheel distribution.

Would you be interested in a PR containing these scripts?

**Comment by osandov** [comment]
We now provide manylinux2010 wheels: https://pypi.org/project/drgn/#files.
