### ISSUE TITLE
Recent libkdumpfile changes breaks drgn for kdumps

### ISSUE THREAD

**Issue by sdimitro** [osandov/drgn#75]
The latest successful SDB nightly was 2 days ago: https://github.com/delphix/sdb/actions/runs/307613188
Yesterday the nightly failed (https://github.com/delphix/sdb/runs/1265111694?check_suite_focus=true) because when `drgn` tried to open our regression kdump dump to run the tests we got back `VMCOREINFO does not contain valid OSRELEASE`.

Since it seems like libkdumpfile was the only repo that had changes during that time I've started looking into some of these changes that look suspicious. This could be a regression on the `drgn` kdump code if the API changed but it could also be a bug in the new libkdumpfile code. In any case I wanted to create this issue here for reference.

**Comment by sdimitro** [comment]
I just realized that I don't have permissions to set the assignee so however reads that and has access feel free to assign this issue to me.

**Comment by sdimitro** [comment]
As an update this seems to have originated by https://github.com/ptesarik/libkdumpfile/commit/b4b3c94cc24dc88d08701ebe35f72a1f1785046a

**Comment by osandov** [comment]
Fixed by bc85c2da08b2215eea1975f0d2d1168eeab51d71.
