### ISSUE TITLE
accessing global percpu variables fails with "address is not mapped"

### ISSUE THREAD

**Issue by danieljordan10** [osandov/drgn#77]
Hello,

I'm trying to access the global percpu variable 'runqueues' on a VM running a 5.9 kernel.  The kernel is configured with the things drgn expects, at least according to `vmtest/config`.

> \>>> prog['runqueues']
Traceback (most recent call last):
  File "\<console\>", line 1, in \<module\>
  File "/home/dmjordan/src/drgn/drgn/internal/cli.py", line 25, in displayhook
    text = value.format_(columns=shutil.get_terminal_size((0, 0)).columns)
_drgn.FaultError: address is not mapped: 0x1eb440

Using the per_cpu_ptr helper fails in a similar way:

> \>>> drgn.helpers.linux.percpu.per_cpu_ptr(prog['runqueues'], 0)
Traceback (most recent call last):
  File "\<console\>", line 1, in \<module\>
  File "/home/dmjordan/src/drgn/drgn/helpers/linux/percpu.py", line 31, in per_cpu_ptr
    return Object(ptr.prog_, ptr.type_, value=ptr.value_() + offset)
_drgn.FaultError: address is not mapped: 0x1eb440

Using plain gdb confirms that 0x1eb440 is the address of `runqueues`.

I've tried a few other global percpu variables with the same results.

drgn is ok with percpu vars when they're hanging off a structure (i.e. from `__alloc_percpu`):

> \>>> prog['async_pf_cache'].cpu_slab
(struct kmem_cache_cpu *)0x1f3a00

> \>>> drgn.helpers.linux.percpu.per_cpu_ptr(prog['async_pf_cache'].cpu_slab, 0)
*(struct kmem_cache_cpu *)0xffff88803dff3a00 = {
	.freelist = (void **)0x0,
	.tid = (unsigned long)0,
	.page = (struct page *)0x0,
	.partial = (struct page *)0x0,
}

I wonder whether there's something wrong with my syntax, or if this is actually a problem with drgn.  Thanks for looking.

**Comment by osandov** [comment]
`per_cpu_ptr()` expects a pointer, so you want `per_cpu_ptr(prog["runqueues"].address_of_(), 0)`.

However, if your kernel has KASLR enabled, this doesn't quite work. I haven't fixed this in drgn yet, but you can use this workaround for now:

```python3
from drgn.helpers.linux.percpu import per_cpu_ptr

def per_cpu_global(prog, name, cpu):
    ptr = prog[name].address_of_()
    ptr = Object(prog, ptr.type_, ptr.value_() - kaslr_offset(prog))
    return per_cpu_ptr(ptr, cpu)
```

Then, `per_cpu_global(prog, "runqueues", 0)` should work whether or not KASLR is enabled.

**Comment by danieljordan10** [comment]
(Hm, for some reason github didn't notify me about your response despite it apparently being configured to do so, sorry for the delay.)

I see!  `DEFINE_PER_CPU_*` doesn't define a pointer, so of course you need the address, and it would've taken me a while to figure out `address_of_()`.  Thanks for your help.

No KASLR workaround needed but good to have anyway.

**Comment by osandov** [comment]
To close the loop on this, I just fixed the KASLR bug, added a [`per_cpu()`](https://drgn.readthedocs.io/en/latest/helpers.html#drgn.helpers.linux.percpu.per_cpu) helper that can be used for globals, and clarified the documentation a bit.
