### ISSUE TITLE
ValueError: not an ELF core file

### ISSUE THREAD

**Issue by ericjoy1** [osandov/drgn#88]
Hi all,
I install libkdumpfile and drgn in a debian buster docker container, but when run drgn -k, the below error messages show:
root@f2871d330b6d:~# drgn -k
Traceback (most recent call last):
  File "/usr/local/bin/drgn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/drgn/internal/cli.py", line 115, in main
    prog.set_kernel()
ValueError: not an ELF core file

BTW, this is my first time to use drgn to want to debug the running kernel, I wonder if the drgn can't be used in container ?

**Comment by osandov** [comment]
`drgn -k` requires `/proc/kcore` to be accessible, which is not the case in most container setups. (It would be a security risk if root inside a container could read from arbitrary kernel memory.)

Could you please share the output of running the following commands as root inside the container?

```
xxd /proc/kcore | head
stat /proc/kcore
stat -f /proc/kcore
findmnt -T /proc/kcore
```

**Comment by ericjoy1** [comment]
@osandov Thanks for your reply, the output of xxd in the container:
root@0228b2962cdb:~# xxd /proc/kcore | head
root@0228b2962cdb:~# cat /proc/kcore 
So there is nothing... so the root cause is the /proc/kcore

Then I append --privileged option to `docker run`, drgn -k command works : )
Thanks for your help ! I will close this issue.

**Comment by ericjoy1** [comment]
I tried some other objects, it looks like works fine, the above 'runqueues' error maybe due to it's a percpu var, I will go on to look the documentation.
>>> prog['autogroup_default']
(struct autogroup){
	.kref = (struct kref){
		.refcount = (refcount_t){
			.refs = (atomic_t){
				.counter = (int)600,
			},
		},
	},
	.tg = (struct task_group *)root_task_group+0x0 = 0xffffffff85607dc0,
	.lock = (struct rw_semaphore){
		.count = (atomic_long_t){
			.counter = (s64)0,
		},
		.owner = (atomic_long_t){
			.counter = (s64)0,
		},
		.osq = (struct optimistic_spin_queue){
			.tail = (atomic_t){
				.counter = (int)0,
			},
		},
		.wait_lock = (raw_spinlock_t){
			.raw_lock = (arch_spinlock_t){
				.val = (atomic_t){
					.counter = (int)0,
				},
				.locked = (u8)0,
				.pending = (u8)0,
				.locked_pending = (u16)0,
				.tail = (u16)0,
			},
		},
		.wait_list = (struct list_head){
			.next = (struct list_head *)autogroup_default+0x28 = 0xffffffff8560a248,
			.prev = (struct list_head *)autogroup_default+0x28 = 0xffffffff8560a248,
		},
	},
	.id = (unsigned long)0,
	.nice = (int)0,
}

**Comment by osandov** [comment]
Yup, per-CPU variables need to be accessed through a helper. You reminded me that I had some pending work in this area that I just pushed. If you rebuild the master branch from source, you can use `per_cpu()`:

```pycon
>>> per_cpu(prog["runqueues"], 6).curr.comm
(char [16])"python3"
```

The released versions of drgn don't have that [helper](https://github.com/osandov/drgn/commit/5f170ea3f39efae65cd082e17c902f65237f94ef), and they also have a [bug](https://github.com/osandov/drgn/commit/2c612ea97fa490d0a8d6577383bbf5dd44486b18) that I just fixed, so if you can't rebuild from source, you need to use this workaround:

```python3
def per_cpu(var, cpu):
    ptr = var.address_of_()
    ptr = Object(prog, ptr.type_, ptr.value_() - kaslr_offset(prog))
    return per_cpu_ptr(ptr, cpu)
```

**Comment by ericjoy1** [comment]
@osandov This is very helpful! Thank you.
