### ISSUE TITLE
Add drgn.Thread API

### ISSUE THREAD

**Issue by osandov** [osandov/drgn#92]
## Problem Statement

drgn currently has no representation of a thread. The only thread-specific operation at the moment is getting a stack trace, which takes a TID to identify the thread:

```pycon
>>> prog.stack_trace(1)
#0  __schedule+0x231/0x654
#1  schedule+0x29/0xa5
#2  schedule_hrtimeout_range_clock+0x18d/0x19c
#3  ep_poll+0x3cd/0x3ec
#4  do_epoll_wait+0xb0/0xc6
#5  __x64_sys_epoll_wait+0x1a/0x1d
#6  do_syscall_64+0x48/0x106
#7  entry_SYSCALL_64+0x7c/0x156
```

When debugging the kernel, it can also take a `struct task_struct *`:

```pycon
>>> task = find_task(prog, 1)
>>> task.type_
struct task_struct *
>>> prog.stack_trace(task)
#0  __schedule+0x231/0x654
#1  schedule+0x29/0xa5
#2  schedule_hrtimeout_range_clock+0x18d/0x19c
#3  ep_poll+0x3cd/0x3ec
#4  do_epoll_wait+0xb0/0xc6
#5  __x64_sys_epoll_wait+0x1a/0x1d
#6  do_syscall_64+0x48/0x106
#7  entry_SYSCALL_64+0x7c/0x156
```

This is fine if you know what TID you want. But, in a lot of cases you probably want/expect the debugger to figure out the interesting TID for you. For example, if you're debugging a core dump, you probably want to look at the thread that segfaulted. We can do that for the kernel with something like:

```pycon
>>> task = per_cpu(prog["runqueues"], prog["crashing_cpu"]).curr
>>> task.type_
struct task_struct *
>>> prog.stack_trace(task)
#0  panic+0x194/0x408
#1  sysrq_handle_crash+0x28/0x2c
#2  __handle_sysrq+0xd0/0x218
#3  write_sysrq_trigger+0xbc/0x108
#4  proc_reg_write+0x90/0xd8
#5  __vfs_write+0x38/0x68
#6  vfs_write+0x11c/0x298
#7  ksys_write+0x84/0x13c
#8  system_call+0x5c/0x0
```

But there's currently no way to do this for userspace core dumps, and even for kernel core dumps it'd be more reliable to get it from the core dump metadata instead.

The goal of this issue is to add generic APIs to represent and find threads in drgn.

## API

This is currently what I have in mind as the MVP (which we may of course want to tweak):

```python3
class Program:
    def thread(self, tid: int) -> Thread:
        """Get the thread with the given thread ID."""
        ...

    def threads(self) -> Iterable[Thread]:
        """Get all threads in the program."""
        ...

    def crashed_thread(self) -> Thread:
        """Get the thread that caused the crash."""
        ...

class Thread:
    tid: int
    """Thread ID."""

    object: Object
    """
    If debugging the kernel, ``struct task_struct *`` object for this thread.
    Otherwise, not defined.
    """

    def stack_trace(self) -> StackTrace:
        """Get the stack trace for this thread."""
        ...
```

And the underlying libdrgn APIs, something like:

```c
struct drgn_thread;
struct drgn_thread_iterator;

struct drgn_error *drgn_program_find_thread(struct drgn_program *prog,
					    uint32_t tid,
					    struct drgn_thread **ret);

struct drgn_error *
drgn_thread_iterator_create(struct drgn_program *prog,
			    struct drgn_thread_iterator **ret);
void drgn_thread_iterator_destroy(struct drgn_thread_iterator *it);
struct drgn_error *drgn_thread_iterator_next(struct drgn_thread_iterator *it,
					     struct drgn_thread **ret);

struct drgn_error *drgn_program_crashed_thread(struct drgn_program *prog,
					       struct drgn_thread **ret);

void drgn_thread_destroy(struct drgn_thread *thread);
uint32_t drgn_thread_tid(struct drgn_thread *thread);
struct drgn_error *drgn_thread_object(struct drgn_thread *thread,
				      struct drgn_object *ret);
struct drgn_error *drgn_thread_stack_trace(struct drgn_thread *thread,
					   struct drgn_stack_trace **ret);
```

drgn doesn't support stack traces of live userspace processes yet, so for now we only need this new interface to support the live kernel, kernel core dumps, and userspace core dumps.

## Implementation

The implementation of these APIs will be different depending on what we're debugging.

### Background

Linux core dumps use the ELF format, which can contain metadata in "note" segments. For a core dump, this metadata includes what threads the process had and what the state of the registers were, among other things:

```
$ eu-readelf --notes core

Note segment of 3356 bytes at offset 0x510:
  Owner          Data size  Type
  CORE                 336  PRSTATUS
    info.si_signo: 11, info.si_code: 0, info.si_errno: 0, cursig: 11
    sigpend: <>
    sighold: <>
    pid: 1120070, ppid: 1120030, pgrp: 1120070, sid: 1120030
    utime: 0.000000, stime: 0.003308, cutime: 0.000000, cstime: 0.000000
    orig_rax: -1, fpvalid: 1
    r15:                       0  r14:                       0
    r13:                       0  r12:                 4198480
    rbp:      0x00007ffebac7ae20  rbx:                 4198816
    r11:                     582  r10:                 1120070
    r9:          140732032060353  r8:                        0
    rax:                    4660  rcx:                       0
    rdx:                       0  rsi:         140732032060720
    rdi:         140281380410560  rip:      0x000000000040113f
    rflags:   0x0000000000010206  rsp:      0x00007ffebac7ae20
    fs.base:   0x00007f95cdd9b580  gs.base:   0x0000000000000000
    cs: 0x0033  ss: 0x002b  ds: 0x0000  es: 0x0000  fs: 0x0000  gs: 0x0000
  CORE                 136  PRPSINFO
    state: 0, sname: R, zomb: 0, nice: 0, flag: 0x0000000000400600
    uid: 1000, gid: 985, pid: 1120070, ppid: 1120030, pgrp: 1120070
    sid: 1120030
    fname: crashme, psargs: ./crashme 
  CORE                 128  SIGINFO
    si_signo: 11, si_errno: 0, si_code: 1
    fault address: 0x1234
  CORE                 320  AUXV
    SYSINFO_EHDR: 0x7ffebacce000
    HWCAP: 0xbfebfbff  <fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe>
    PAGESZ: 4096
    CLKTCK: 100
    PHDR: 0x400040
    PHENT: 56
    PHNUM: 13
    BASE: 0x7f95cddbb000
    FLAGS: 0
    ENTRY: 0x401050
    UID: 1000
    EUID: 1000
    GID: 985
    EGID: 985
    SECURE: 0
    RANDOM: 0x7ffebac7b219
    26: 0x2
    EXECFN: 0x7ffebac7bfee
    PLATFORM: 0x7ffebac7b229
    NULL
  CORE                 696  FILE
    15 files:
      00400000-00401000 00000000 4096                /home/osandov/crashme
      00401000-00402000 00001000 4096                /home/osandov/crashme
      00402000-00403000 00002000 4096                /home/osandov/crashme
      00403000-00404000 00002000 4096                /home/osandov/crashme
      00404000-00405000 00003000 4096                /home/osandov/crashme
      7f95cdbcd000-7f95cdbf3000 00000000 155648      /usr/lib/libc-2.33.so
      7f95cdbf3000-7f95cdd3f000 00026000 1359872     /usr/lib/libc-2.33.so
      7f95cdd3f000-7f95cdd8b000 00172000 311296      /usr/lib/libc-2.33.so
      7f95cdd8b000-7f95cdd8e000 001bd000 12288       /usr/lib/libc-2.33.so
      7f95cdd8e000-7f95cdd91000 001c0000 12288       /usr/lib/libc-2.33.so
      7f95cddbb000-7f95cddbc000 00000000 4096        /usr/lib/ld-2.33.so
      7f95cddbc000-7f95cdde0000 00001000 147456      /usr/lib/ld-2.33.so
      7f95cdde0000-7f95cdde9000 00025000 36864       /usr/lib/ld-2.33.so
      7f95cddea000-7f95cddec000 0002e000 8192        /usr/lib/ld-2.33.so
      7f95cddec000-7f95cddee000 00030000 8192        /usr/lib/ld-2.33.so
  CORE                 512  FPREGSET
    xmm0:  0x25252525252525252525252525252525
    xmm1:  0xffff00ffffff0000000000ffffffff00
    xmm2:  0xffff00ffffff0000000000ffffffff00
    xmm3:  0x0000000000000000000000000000ff00
    xmm4:  0x2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f
    xmm5:  0x00000000000000000000000000000000
    xmm6:  0x00000000000000000000000000000000
    xmm7:  0x00000000000000000000000000000000
    xmm8:  0x000009000000543b031b01000000000a
    xmm9:  0x00000000000000000000000000000000
    xmm10: 0x00000000000000000000000000000000
    xmm11: 0x00000000000000000000000000000000
    xmm12: 0x00000000000000000000000000000000
    xmm13: 0x00000000000000000000000000000000
    xmm14: 0x00000000000000000000000000000000
    xmm15: 0x00000000000000000000000000000000
    st0: 0x00000000000000000000  st1: 0x00000000000000000000
    st2: 0x00000000000000000000  st3: 0x00000000000000000000
    st4: 0x00000000000000000000  st5: 0x00000000000000000000
    st6: 0x00000000000000000000  st7: 0x00000000000000000000
    mxcsr:   0x0000ffff00001f80
    fcw: 0x037f  fsw: 0x0000
  LINUX               1088  X86_XSTATE
```

The most relevant note for this project is the `PRSTATUS` note, which is what drgn uses to start a stack trace. `struct drgn_thread` will probably want to store the `PRSTATUS` note for the thread.

### Kernel

For the kernel, a `struct drgn_thread` also needs the `struct task_struct *` object.

* `drgn_program_find_thread()` needs to find the `struct task_struct *` (with `linux_helper_find_task()`) and wrap it in a `struct drgn_thread`.
* The thread iterator needs to iterate over all tasks and wrap each one in a `struct drgn_thread`. We have a `for_each_task()` helper implemented in Python, but that will need to be translated to C so that it can be used in libdrgn (including its dependencies: `for_each_pid()`, `idr_for_each()`, `radix_tree_for_each()`).
* `drgn_program_crashed_thread()` needs to get the value of `crashing_cpu` and find the corresponding `PRSTATUS` note and TID with `drgn_program_find_prstatus_by_cpu()`, then it's pretty much equivalent to `drgn_program_find_thread()`. Obviously, this won't apply when debugging the live kernel.

### Userspace Core Dumps

* `drgn_program_find_thread()` needs to find the `PRSTATUS` note with `drgn_program_find_prstatus_by_tid()` and save it in a `struct drgn_thread`.
* The thread iterator needs to iterate over all `PRSTATUS` notes and save each one in a `struct drgn_thread`.
* `drgn_program_crashed_thread()` needs to determine which thread crashed and wrap its `PRSTATUS` note. From what I can tell, Linux puts the crashed `PRSTATUS` first in the core dump, but this needs to be verified.

### Python Bindings

The bulk of the implementation will be in libdrgn, but there will need to be some boilerplate Python bindings.

## Future Directions

* A `Thread.name` attribute containing the `comm` of the thread.
* A `Program` method to get all threads that were running at the time of the crash (or better yet, a mapping from CPU number to the thread that was running on that CPU). This would probably have to be kernel-only, as I don't know of a way to get that information from a userspace core dump.
* Support for live userspace processes, including `Thread.pause()` and `Thread.resume()` methods.
* `Thread.object` for userspace programs (maybe as the `pthread_t` if using pthreads?).

**Comment by Svetlitski-FB** [comment]
I'll get started on this @osandov
